### ISSUE TITLE
Migrate to MIT License

### ISSUE THREAD

**Issue by maiha** [puppetpies/crystal-libpcap#2]
Hi Brian!
Do you hava any plans to change license to MIT?
I'd like to use only `libpcap.cr` in my apps and libs where licenses are almost MIT.

This is just a question. So feel free to reject :)
Thanks.

**Comment by puppetpies** [comment]
Hi maiha,

Seen as MIT license has compatibility with GPL see no reason to change it.

I've have just changed it here are the commits.

https://github.com/puppetpies/crystal-libpcap/compare/1ab79f1ab0...e893a4afe9

Regards,

Brian

**Comment by maiha** [comment]
Thanks a lot!
